#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. /pm:prd-new <name>        - Create a new PRD"
echo "  2. /pm:prd-parse <name>      - Convert PRD to epic"
echo "  3. /pm:epic-oneshot <name>   - Decompose + sync to GitHub"
echo "  4. /pm:epic-start <name>     - Start epic (loads context, creates branch)"
echo "  5. /pm:issue-start <num>     - Start work on an issue"
echo "  6. /pm:issue-complete <num>  - Complete issue (handoff + verify + close)"
echo "  7. /pm:epic-verify <name>    - Verify epic (Phase A + Phase B)"
echo "  8. /pm:epic-merge <name>     - Merge epic to main"
echo ""
echo "📄 PRD Commands"
echo "  /pm:prd-new <name>     - Launch brainstorming for new product requirement"
echo "  /pm:prd-parse <name>   - Convert PRD to implementation epic"
echo "  /pm:prd-list           - List all PRDs"
echo "  /pm:prd-edit <name>    - Edit existing PRD"
echo "  /pm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  /pm:epic-decompose <name> - Break epic into task files"
echo "  /pm:epic-sync <name>      - Push epic and tasks to GitHub"
echo "  /pm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /pm:epic-list             - List all epics"
echo "  /pm:epic-show <name>      - Display epic and its tasks"
echo "  /pm:epic-status [name]    - Show epic progress"
echo "  /pm:epic-start <name>     - Start epic (loads context, creates branch)"
echo "  /pm:epic-close <name>     - Mark epic as complete"
echo "  /pm:epic-edit <name>      - Edit epic details"
echo "  /pm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /pm:epic-merge <name>     - Merge completed epic to main"
echo ""
echo "📝 Issue Commands"
echo "  /pm:issue-show <num>      - Display issue and sub-issues"
echo "  /pm:issue-status <num>    - Check issue status"
echo "  /pm:issue-start <num>     - Begin work (loads context)"
echo "  /pm:issue-analyze <num>   - Analyze for parallel work streams"
echo "  /pm:issue-sync <num>      - Push updates to GitHub"
echo "  /pm:issue-complete <num>  - Complete (handoff + verify + close)"
echo "  /pm:issue-close <num>     - Close issue on GitHub"
echo "  /pm:issue-reopen <num>    - Reopen closed issue"
echo "  /pm:issue-edit <num>      - Edit issue details"
echo ""
echo "🔍 Verification Commands (Issue-level)"
echo "  /pm:verify-run             - Run verification checks"
echo "  /pm:verify-status          - Show current verify state"
echo "  /pm:verify-skip <reason>   - Skip verification with reason"
echo ""
echo "🔍 Verification Commands (Epic-level)"
echo "  /pm:epic-verify <name>         - Full pipeline (Phase A + Phase B)"
echo "  /pm:epic-verify-a <name>       - Phase A only (semantic review)"
echo "  /pm:epic-verify-b <name>       - Phase B only (integration tests)"
echo "  /pm:epic-verify-status <name>  - Current verify state"
echo "  /pm:epic-verify-report <name>  - View latest report"
echo "  /pm:epic-verify-history <name> - View all past reports"
echo "  /pm:epic-verify-resume <name>  - Resume aborted verify"
echo "  /pm:epic-verify-abort <name>   - Abort running verify"
echo "  /pm:epic-gaps <name>           - View gap report"
echo "  /pm:epic-coverage <name>       - View coverage matrix"
echo "  /pm:epic-accept-gaps <name>    - Accept gaps as tech debt"
echo "  /pm:epic-fix-gap <name>        - Create issue from gap"
echo ""
echo "📋 Context & Handoff Commands"
echo "  /pm:handoff-write        - Write handoff notes for next session"
echo "  /pm:handoff-show         - Display latest handoff note"
echo "  /pm:context-health       - Diagnostics on context files"
echo "  /pm:context-reset        - Safe context clear with protocol"
echo ""
echo "🔄 Workflow Commands"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  /pm:sync               - Full bidirectional sync with GitHub"
echo "  /pm:import <issue>     - Import existing GitHub issues"
echo ""
echo "🔧 Maintenance Commands"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /pm:init               - Install dependencies and configure GitHub"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • Full workflow: prd-new → prd-parse → epic-oneshot → epic-start → issue-start → issue-complete → epic-verify → epic-merge"
echo "  • View README.md for complete documentation"

exit 0
