#!/usr/bin/env bash
# acceptance.sh — Manual E2E acceptance test checklist for dx-hardening epic
#
# Usage: bash tests/e2e/epic_dx-hardening/acceptance.sh
#
# This script prints a manual checklist. Each item requires human verification.
# Run each test, observe the behavior, and mark it complete.

echo "=== DX Hardening E2E Acceptance Test ==="
echo "Epic: dx-hardening (T181–T189)"
echo ""
echo "Run each test manually in your Claude Code session and verify the behavior."
echo "Mark each item [ ] → [x] once verified."
echo ""
echo "─── pm:build ──────────────────────────────────────────────────────────"
echo "[ ] 1. /pm:build test-e2e"
echo "       Expected: starts workflow, pauses at first gate (prd-qualify)"
echo "       Expected: shows step progress indicator"
echo ""
echo "[ ] 2. /pm:build --dry-run test-e2e"
echo "       Expected: shows all 10 steps with gate positions"
echo "       Expected: shows token estimate per step (no execution)"
echo ""
echo "[ ] 3. /pm:build --resume test-e2e"
echo "       Expected: resumes from last checkpoint (reads .claude/context/build-state/)"
echo "       Expected: skips already-completed steps"
echo ""
echo "[ ] 4. /pm:build --no-gate=plan-review test-e2e"
echo "       Expected: skips plan-review gate, continues automatically"
echo ""
echo "─── pm:next ────────────────────────────────────────────────────────────"
echo "[ ] 5. /pm:next (no arguments)"
echo "       Expected: context-aware suggestion based on project state"
echo "       Expected: runs next.sh --smart (0 LLM tokens)"
echo ""
echo "[ ] 6. /pm:next 'create a new PRD for feature X'"
echo "       Expected: suggests /pm:prd-new with [heavy/opus] annotation"
echo ""
echo "[ ] 7. /pm:next 'what should I do next'"
echo "       Expected: discovers relevant command from catalog"
echo ""
echo "─── pm:budget ──────────────────────────────────────────────────────────"
echo "[ ] 8. /pm:budget test-e2e"
echo "       Expected: shows token estimate table for each workflow step"
echo "       Expected: shows TOTAL row with sum"
echo "       Expected: completes instantly (0 LLM tokens)"
echo ""
echo "─── pm:onboard ─────────────────────────────────────────────────────────"
echo "[ ] 9. /pm:onboard"
echo "       Expected: starts interactive walkthrough with _onboard-demo feature"
echo "       Expected: completes full lifecycle in ≤15 minutes"
echo "       Expected: cleans up _onboard-demo artifacts after completion"
echo ""
echo "─── pm:upstream-sync ───────────────────────────────────────────────────"
echo "[ ] 10. /pm:upstream-sync"
echo "        Expected: fetches changes from upstream automazeio/ccpm"
echo "        Expected: categorizes changes as: apply / skip / conflict"
echo "        Expected: shows summary before applying anything"
echo ""
echo "─── Backward Compatibility ─────────────────────────────────────────────"
echo "[ ] 11. /pm:status"
echo "        Expected: shows current project status (unchanged behavior)"
echo ""
echo "[ ] 12. /pm:standup"
echo "        Expected: generates standup report (unchanged behavior)"
echo ""
echo "[ ] 13. /pm:next <existing-epic>"
echo "        Expected: shows next task for that epic (backward-compatible)"
echo ""
echo "[ ] 14. /pm:epic-list"
echo "        Expected: lists epics (unchanged behavior)"
echo ""
echo "─── NFR-1: Overhead Check ──────────────────────────────────────────────"
echo "[ ] 15. Timing test: /pm:build --dry-run test-nfr"
echo "        Expected: orchestrator step overhead <2s per step"
echo "        Measure: time between 'Step N:' output lines"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo "All 15 items must be verified before marking epic complete."
echo "═══════════════════════════════════════════════════════════════════════"
